# Generated by Django 6.0.5 on 2026-06-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descricao_curta', models.TextField(blank=True)),
                ('descricao_completa', models.TextField(blank=True)),
                ('localizacao_textual', models.CharField(max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ano_construcao', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_pavimentos', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_unidades', models.PositiveIntegerField(blank=True, null=True)),
                ('vagas_estacionamento', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_uso', models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('misto', 'Misto'), ('institucional', 'Institucional')], max_length=30)),
                ('status', models.CharField(blank=True, choices=[('construido', 'Construído'), ('em_construcao', 'Em construção'), ('projeto', 'Projeto'), ('reforma', 'Reforma')], max_length=30)),
                ('estrutura', models.CharField(blank=True, max_length=150)),
                ('sistema_construtivo', models.CharField(blank=True, max_length=150)),
                ('arquiteto', models.CharField(blank=True, max_length=150)),
                ('cliente', models.CharField(blank=True, max_length=150)),
                ('responsaveis_tecnicos', models.TextField(blank=True)),
                ('diferenciais', models.TextField(blank=True)),
                ('observacoes_internas', models.TextField(blank=True)),
                ('visivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edifício',
                'verbose_name_plural': 'Edifícios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='edificios/fotos/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('eh_principal', models.BooleanField(default=False)),
                ('visivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='edificios.edificio')),
            ],
            options={
                'verbose_name': 'Foto do edifício',
                'verbose_name_plural': 'Fotos dos edifícios',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
