# Generated by Django 6.0.5 on 2026-06-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='fotoedificio',
            name='eh_principal',
        ),
        migrations.AlterField(
            model_name='edificio',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='tipo_uso',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
